version: 2
formats:
  - htmlzip
  - pdf
python:
  version: 3.7
  install:
     - requirements: requirements.txt
build:
  image: latest
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false
